Implement cookies and servlet filters
Orbit419/MyJDBC pull request #2
Opened 2019-02-17 12:45 UTC by Orbit419

2019-02-17 21:41 UTC, boroda4436 requested changes

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/controllers/LoginController.java
> +        return securityService.doLogin(request);
@Orbit419 я б не рекомендував прив'язувати SecurityService до нашої реалізації з ViewModel. Краще сформуй ViewModel в самому контроллері, а з SecurityService отримуй інформацію про успішну / не успішну авторизацію

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/controllers/RegistrationController.java
>          return ViewModel.of("registration");
@Orbit419 Якщо у нас реєстрація пройшла успішна - нам необхідно перевести юзера на сторінку логіну щоб він зміг залогінитися в нашу систему

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/service/SecurityService.java
> +    ViewModel doLogin(Request request);
@Orbit419 краще залиш boolean, або взагалі можеш проапдейтити і повертати щось на кшталт UserDetails як у Spring Security. Щодо ViewModel - дивись комент вище

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/service/SecurityServiceImpl.java
> +        Cookie cookie = new Cookie("MATE", userToken);
Краще не треба оперувати Cookie на рівні SecurityService. Так ти дуже жорстко прив'язуєшся конкретно до цієї імплементації. Перенеси їх в контроллер

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/MainServlet.java
> +        if(!vm.getAllCookie().isEmpty()) {
@Orbit419 автоформатування коду пробував?)

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/Request.java
> +    private HttpServletResponse response;
@Orbit419 для чого тобі необхідні HttpServletResponse і HttpServletRequest ? Наша мета для цього класу - симулювати поведінку HttpServletRequest

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/filters/UserFilter.java
> +            , FilterChain filterChain) throws IOException, ServletException {
@Orbit419 кома на початку рядка?) Що про це каже посібник по код стайлу?

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/filters/UserFilter.java
> +            for(Cookie c : cookies) {
Автоформатування коду! Ми розбирали це на перших заняттях. Про нього ніколи не потрібно забувати

2019-02-17 21:41 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/filters/UserFilter.java
> +                if(path.equals("/servlet/login") || path.equals("/servlet/registration")) {
@Orbit419 для чого тут додаткова перевірка? Чому не можна просто використати processAuthorized(req, resp, filterChain); ?

2019-02-18 07:46 UTC, Orbit419 commented on src/main/java/mate/academy/myJdbc/web/Request.java
> +    private HttpServletResponse response;
Они нужны для того, чтобы вынести куки в HttpServletResponse. У меня операции с куки находятся в самом низу, а добирается туда только реквест.

2019-02-18 07:46 UTC, Orbit419 commented on src/main/java/mate/academy/myJdbc/controllers/LoginController.java
> +        return securityService.doLogin(request);
я с помощью ViewModel вытягиваю куки в респонс

2019-02-18 09:05 UTC, Orbit419 commented on src/main/java/mate/academy/myJdbc/web/filters/UserFilter.java
> +                if(path.equals("/servlet/login") || path.equals("/servlet/registration")) {
это редирект на home. если уже залогинен и хочешь зайти на логин

2019-02-18 09:27 UTC, boroda4436 approved these changes
LGTM

2019-02-18 09:29 UTC, merged