implement security roles
Orbit419/MyJDBC pull request #3
Opened 2019-02-21 10:38 UTC by Orbit419

2019-02-21 11:44 UTC, boroda4436 requested changes

2019-02-21 11:44 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/MainServlet.java
> +        if (!vm.getView().equals("")) {
@Orbit419 не зовсім зрозуміло чому тут йде перевірка на пусту строку

2019-02-21 11:44 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/web/filters/UserFilter.java
> +                    resp.sendRedirect("/jdbcdemo_war_exploded/servlet/home");
@Orbit419 Спробуй в налаштуваннях томкет прибрати _jdbcdemo_war_exploded_  там де URL і запустити. Тоді ти зможеш прибрати jdbcdemo_war_exploded з коду

2019-02-21 11:44 UTC, boroda4436 commented on src/main/java/mate/academy/myJdbc/service/RoleServiceImpl.java
> +    public void addRoleToUser(Long userId, Long roleId) {
@Orbit419 А де ти викликаєш цей метод?

2019-02-21 15:47 UTC, Orbit419 commented on src/main/java/mate/academy/myJdbc/web/MainServlet.java
> +        if (!vm.getView().equals("")) {
У меня бывает токен MATE с таким значениям. Я не знаю как оно происходит такое, но я во всех примерах в инете тоже видел такую проверку. В общем это действительно нужно

2019-02-24 08:52 UTC, boroda4436 approved these changes
LGTM

2019-02-24 09:00 UTC, merged